### ISSUE TITLE
Send Message URL Scheme not working on app launch

### ISSUE THREAD

**Issue by de1mat** [TelegramMessenger/Telegram-iOS#106]
Yes #15 is related. #15 is fixed if Telegram is already running in the background.

This issue is specifically about when Telegram is **not** running in the background.

If you force close Telegram, and then trigger the URL Scheme `tg://msg?text=Hello&to=+42333`, then Telegram opens, but the scheme is not activated.

**Comment by laktyushin** [comment]
Fixed in 5.10 release.

**Comment by de1mat** [comment]
I just installed 5.10. The issue is not fixed. It is the same as before...

**Comment by Jheank16oz** [comment]
It  is not fixed yet

**Comment by elhe26** [comment]
Still not working.

**Comment by extratone** [comment]
Has Telegram published documentation of any kind regarding its properties URL scheme support?

**Comment by capecrawler** [comment]
We tried it out and the message url scheme doesn't work if the telegram app is launch as "cold start".
Having it running previously or in background, the message url scheme works. Thus, user will have to try at most twice for this to work.
