### ISSUE TITLE
The video preview and playback only display a static image

### ISSUE THREAD

**Issue by FRNVR** [TelegramMessenger/Telegram-iOS#1625]
### Description
After the recent update to version 11.4, videos are just showing a static image

### Steps to Reproduce
Open channel or a private message containing a video

### Actual Behavior
When opening a channel or a private message containing a video, both the video preview and playback show only a static image. However, these videos function correctly on Telegram's desktop version

### Expected Behavior
The video preview and opened video work correctly.

### Environment
**Device:** `iPhone

**iOS version**: `18.1`

**App version:** `11.4,`

**Comment by ali-fareed** [comment]
Fixed.

**Comment by tamtamree** [comment]
iphone 7, ios 15.8.3
still have this issue, tried reinstalling the app.
static image only on new videos, old videos in my chats and favourites are working normally.
P.S. videos play normally in mini-player

**Comment by ivanstepanovftw** [comment]
Any regressions in 2026?
