### ISSUE TITLE
Text for photos is shared as a separate message

### ISSUE THREAD

**Issue by WhyNotHugo** [TelegramMessenger/Telegram-iOS#311]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description

When I share a photo from anywhere (e.g.: Photos app), I can type a message to go as a caption:

![image](https://user-images.githubusercontent.com/730811/84597640-e32bb600-ae54-11ea-9a5c-000d5e80e6e4.png)
(had to blur contact details due to third-party privacy)

When sharing to most apps, this is set as a caption for the shared photo.

### Actual Behavior

The message is sent as a separate message, not a photo caption. It's also send _before_ the photo, which can result confusing if the photo takes a short while to be sent out:

![image](https://user-images.githubusercontent.com/730811/84597684-30a82300-ae55-11ea-9ad1-dadff4c7641a.png)

### Expected Behavior

I'd expect the text to be set as a photo caption (message edited manually for this screenshot):

![image](https://user-images.githubusercontent.com/730811/84597674-1d955300-ae55-11ea-8c4c-d26d4567e1da.png)

### Steps to Reproduce
1. Open any app that allows sharing a photo (e.g.: stock Photos app).
2. Tap share
3. Tap on a Telegram contact
4. Cap a caption for the photo
5. Tap send.

### Environment
**Device:** `iPhone 11 Pro`

**iOS version**: `13.5`

**App version:** `6.2.1`

**Comment by lonsdaleite** [comment]
Up the issue. 
It also affects a communication with bots. Some bots can handle an image with caption but not two messages.

**Comment by laktyushin** [comment]
Fixed.

**Comment by haasn** [comment]
> Fixed.

Why was this closed as fixed? As far as I can tell the bug is still present as of version `9.0.2`.
