### ISSUE TITLE
Crash when editing photo

### ISSUE THREAD

**Issue by Neurotoxin001** [TelegramMessenger/Telegram-iOS#397]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
When you editing photo or video and press to "add sticker" icon - you got crash.

### Steps to Reproduce
1. Delete all masks packs from the stickers settings
2. Try to edit photo/video and click to "add sticker" icon
3. Crash
4. If you have at least 1 mask pack - all is fine.

### Environment
**Device:** iPhone XR

**iOS version**: 4.0.1

**App version:** 7.1.2 (crashes appear at this version)

**Comment by Neurotoxin001** [comment]
Still in 7.2

**Comment by tubebela** [comment]
Environment
Device: iPhone 11 Pro
iOS version: 13.5.1
App version: 7.2( Also Happen in previous version)



Also, Adding Text on photo and the Text Show on Worng Place.
Device: iPhone 11 Pro 
iOS version: 13.5.1 
App version: 7.2

Device: iPhone 6S
iOS version: 13.6
App version: 7.1.2

02 Nov 2020

**Comment by laktyushin** [comment]
Fixed in 7.2.1

**Comment by anupoju84** [comment]
The issue is still present. I edit a pic and add some smileys to it and when I try to send the pic, the app crashes and never opens in my iPhone (7 plus).
