### ISSUE TITLE
t.me links do not work on iOS

### ISSUE THREAD

**Issue by alectprasad** [TelegramMessenger/Telegram-iOS#439]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
t.me links do not open in safari or direct to app

### Expected Behavior
link should open the app

### Actual Behavior
safari cannot load the page because a secure connection cannot be established

### Steps to Reproduce
1.  Visit any t.me link

### Screenshots and Videos 
https://i.imgur.com/BX6lS00.jpg

### Environment
**Device:** `iPhone 11`

**iOS version**: `14.3`

**App version:** `7.3.1`

**Comment by anantakrishna** [comment]
I guess it is due to the Telegram web is blocked in some countries, including India. https://support.google.com/youtube/thread/2871901?hl=en&msgid=39451280

**Comment by kdosu** [comment]
ok

**Comment by laktyushin** [comment]
Fixed.

**Comment by max-programming** [comment]
The `t.me` links still don't work for me.
One fix I found is to replace `t` to `telegram` in the link and that works properly

`telegram.me/***`
