### ISSUE TITLE
A valid provisioning profile for this executable was not found (xcode)

### ISSUE THREAD

**Issue by jalalimehdi** [TelegramMessenger/Telegram-iOS#752]
### Checklist
- [x] I am reporting an issue in existing functionality that does not work as intended
- [x] I've searched for existing [GitHub issues](https://github.com/telegrammessenger/Telegram-iOS/issues)

### Description
`A valid provisioning profile for this executable was not found.`
I receive the above error, despite having a valid provisioning profile which, as far as I can tell matches the bundle identifier.
I encountered this problem when I was trying to test on  my iPhone.
I of course updated the app's development and distribution profiles to use these new certificates and made sure to re-download them to my workstation.
I simply had to use a Distribution Profile of type Ad Hoc. 
I know this has been asked and answered multiple times but I'm tearing my hair out as none of the proposed solutions appears to work.
refer to this post: [stackoverflow.com/questions/52424462/](https://stackoverflow.com/questions/52424462/xcode-10-a-valid-provisioning-profile-for-this-executable-was-not-found)

### Expected Behavior
App launches  in actual device

### Actual Behavior
`A valid provisioning profile for this executable was not found.`
<img width="357" alt="Screen Shot 2022-04-12 at 2 42 57 AM" src="https://user-images.githubusercontent.com/4976108/162845493-8d66a4c7-aa6f-42cc-adf8-6f8716d7d296.png">

### Steps to Reproduce
1. Build the app (I succeeded to build the app)
```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    build \
    --configurationPath="$HOME/telegram-configuration" \
    --buildNumber=100001 \
    --configuration=release_universal
```
2.I generated the project with this command 
```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration" \
    --disableExtensions
```
3. App launches  in simulator
4. App isn't launches  in actual device

### Screenshots and Videos 

<img width="616" alt="Screen Shot 2022-04-12 at 3 06 07 AM" src="https://user-images.githubusercontent.com/4976108/162845417-3c8cca09-09e1-4814-8635-ba6e140ebcc6.png">

<img width="427" alt="Screen Shot 2022-04-12 at 2 58 58 AM" src="https://user-images.githubusercontent.com/4976108/162845770-6e033d2a-aaa8-4913-bbee-0ca932fe6d8a.png">

### Environment
**App version: **` 8.6.1`

**Bazel version: ** `5.1.0`

**xCode version: ** `13.2.1`

**MacOS version: ** `12.3.1`

**Comment by shivanraptor** [comment]
If you try to debug the app via Xcode, you should let Xcode manage the signing identity automatically.

**Comment by jalalimehdi** [comment]
Hi @shivanraptor 
when I try to debug the app via Xcode and 
Xcode manage the signing identity automatically

My Debug Area logs
```
2022-04-13 11:30:04.554526+0430 Telegram[14071:5511012] [Warning] Trying to set delaysTouchesBegan to NO on a system gate gesture recognizer - this is unsupported and will have undesired side effects
2022-04-13 11:30:04.578307+0430 Telegram[14071:5511012] [unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
Architecture: arm64
Embedded signature, length: 4876
2022-04-13 11:30:04.591616+0430 Telegram[14071:5511012] [Presentation] Attempt to present <UIAlertController: 0x10602ae00> on <_TtC7DisplayP33_83BFFE1175986BF91B85BE8424379B0424WindowRootViewController: 0x10360f0d0> (from <_TtC7DisplayP33_83BFFE1175986BF91B85BE8424379B0424WindowRootViewController: 0x10360f0d0>) whose view is not in the window hierarchy.
```
app has black screen on device. works fine on simulator. 
Launch my device from Xcode and getting a black screen
I taked a  screenshot
![IMG_5297](https://user-images.githubusercontent.com/4976108/163119587-48a59340-b4f3-44dd-a02b-4eb5f6e64a41.PNG)

**Comment by kebbbnnn** [comment]
> Hi @shivanraptor when I try to debug the app via Xcode and Xcode manage the signing identity automatically
> 
> My Debug Area logs
> 
> ```
> 2022-04-13 11:30:04.554526+0430 Telegram[14071:5511012] [Warning] Trying to set delaysTouchesBegan to NO on a system gate gesture recognizer - this is unsupported and will have undesired side effects
> 2022-04-13 11:30:04.578307+0430 Telegram[14071:5511012] [unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
> Architecture: arm64
> Embedded signature, length: 4876
> 2022-04-13 11:30:04.591616+0430 Telegram[14071:5511012] [Presentation] Attempt to present <UIAlertController: 0x10602ae00> on <_TtC7DisplayP33_83BFFE1175986BF91B85BE8424379B0424WindowRootViewController: 0x10360f0d0> (from <_TtC7DisplayP33_83BFFE1175986BF91B85BE8424379B0424WindowRootViewController: 0x10360f0d0>) whose view is not in the window hierarchy.
> ```
> 
> app has black screen on device. works fine on simulator. Launch my device from Xcode and getting a black screen I taked a screenshot ![IMG_5297](https://user-images.githubusercontent.com/4976108/163119587-48a59340-b4f3-44dd-a02b-4eb5f6e64a41.PNG) <img alt="Screen Shot 2022-04-13 at 12 12 54 PM" width="943" src="https://user-images.githubusercontent.com/4976108/163125728-075a2894-f21f-4318-82b3-fd491486d0da.png">

Hi, how did you manage to run it on device? I tried ticking the signing identity automatically and added required capabilities but still got same error. Thank you in advance

**Comment by kebbbnnn** [comment]
Never mind, I've fixed it. For those who encountered this issue this is what I did.

**Step 1**: Go to apple dev portal and generate new certificate for development then download and add it to your keychain. Generate new provisioning profiles for the app targeting that new cert for development.

**Step 2**: Duplicate `telegram-configuration` folder and rename it `telegram-configuration-development` replace all provisioning profiles with the ones that targets development. In the `variables.bzl` file change the value of `telegram_aps_environment` from `production` to `development`

**Step 3**: clean the project with command:

```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    clean
```

then generate the xcode project:

```
python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration-development"
```

And that's it. You can now select your iOS device in your target and run the app on your device

**Comment by jalalimehdi** [comment]
Hi @kebbbnnn 
I did all three steps, unfortunately the problem was not solved.


<img width="1138" alt="Screen Shot 2022-05-09 at 8 09 30 PM" src="https://user-images.githubusercontent.com/4976108/167446547-889a323f-1e78-40d1-9898-734fdfc3bb2b.png">
<img width="755" alt="Screen Shot 2022-05-09 at 8 09 49 PM" src="https://user-images.githubusercontent.com/4976108/167446559-a08c4ac7-5452-40e7-a82b-feb016b99222.png">

**Comment by eduhcano** [comment]
Hi @jalalimehdi I am stuck in that black screen too, did you manage to solve it?

**Comment by liujia1993** [comment]
@kebbbnnn  Can you help me out~
da@DadeMacBook-Pro Telegram-iOS % python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath="$HOME/telegram-configuration-development"
Traceback (most recent call last):
  File "/Users/da/Telegram-iOS/build-system/Make/Make.py", line 726, in <module>
    generate_project(bazel=bazel_path, arguments=args)
  File "/Users/da/Telegram-iOS/build-system/Make/Make.py", line 414, in generate_project
    bazel_command_line = BazelCommandLine(
  File "/Users/da/Telegram-iOS/build-system/Make/Make.py", line 16, in __init__
    self.build_environment = BuildEnvironment(
  File "/Users/da/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 130, in __init__
    actual_bazel_version = get_bazel_version(self.bazel_path)
  File "/Users/da/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 66, in get_bazel_version
    command_result = run_executable_with_output(bazel_path, ['--version']).strip('\n')
  File "/Users/da/Telegram-iOS/build-system/Make/BuildEnvironment.py", line 36, in run_executable_with_output
    process = subprocess.Popen(
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/da/Telegram-iOS/build-input/bazel-5.1.0-x86_64'

**Comment by caicaibuchicai** [comment]
![111](https://user-images.githubusercontent.com/20339971/218700545-2129e320-73a8-47b3-871f-748c878dcc2d.jpeg)

**Comment by saeedcfc** [comment]
Can you explain more?
in https://developer.apple.com/account/resources/identifiers/list
i create Identifiers and Profiles 
![1](https://user-images.githubusercontent.com/37158491/223400666-146a7d56-e955-41e4-b060-13617f4c75d3.png)
![02](https://user-images.githubusercontent.com/37158491/223400691-c4ed09cb-5926-4022-870b-0e68ab517644.png)
and i change  variables.bzl but after run show this error 
could not find a valid aps-environment entitlement in the provided provisiong profiles
i think my profile and Identifiers create wrong
